version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: psico_postgres
    environment:
      POSTGRES_DB: psico_db
      POSTGRES_USER: psico_user
      POSTGRES_PASSWORD: psico_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - psico_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: psico_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - psico_network

volumes:
  postgres_data:

networks:
  psico_network:
    driver: bridge 