version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: psico_mongodb
    environment:
      MONGO_INITDB_DATABASE: psico_db
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - psico_network

  # mongo-express:
  #   image: mongo-express:latest
  #   container_name: psico_mongo_express
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: psico_user
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: psico_password
  #     ME_CONFIG_MONGODB_URL: mongodb://psico_user:psico_password@mongodb:27017/
  #   ports:
  #     - "8081:8081"
  #   depends_on:
  #     - mongodb
  #   networks:
  #     - psico_network

volumes:
  mongodb_data:

networks:
  psico_network:
    driver: bridge 